### ISSUE TITLE
Add canonical URI to WRAP

### ISSUE THREAD

**Issue by fetsorn** [polywrap/technical-council#69]
wrap.info should contain a canonical URI.
If the client redirects the wrapper to some other URI, the wrapper would still know its canonical URI and able to use it.

**Comment by dOrgJelli** [comment]
I do not think this makes sense. The `wrap.info` manifest already implements a `name`, but to include a `uri` is a strange circular dependency.

This is like saying that a website knows the exact domain + IP it's being hosted at before it's published. In order to get around this the use of `PUBLIC_URL` is used to know what the current domain is.

I think we should instead allow wrappers to fetch their current URI at run-time, effectively `this.uri` within a wrapper's logic. This way the wrapper could be published anywhere, and the URI is always correct.
